### PR TITLE
Location input

### PR DESCRIPTION
**Pull request by NJTuley**
Wanted to get everyone to see the code that implemented the dynamic location input being integrated with the citysdk request, and answer any questions about it, and/or talk about any issues anyone sees in the code

### CODE REVIEW

**Review by NJTuley — COMMENTED** [review]
Changes are all as intended as far as I can tell when I merged master into Location_input, now just to push the new changes into master when all reviewers have reviewed the code

**Comment by mezerotm** [comment]
@NJTuley I remember you telling me you were still having issues with _pulling information_. Can you please better document these issues and how I can replicate them. I don't expect to fix them overnight but I would like to put some fresh eyes on the issue (me)

**Review by hardnett — APPROVED** [review]
I think it all looks fine to me. If there are any bugs then we can work them out. There were come conflicts with my most recent fix, but I cleared that up. For some reason is was finding conflicts with blanks lines before new code.

**Comment by hardnett** [comment]
@NJTuley and @mezerotm If there is an issue with pulling information, then go ahead and create a bug issue for the Alpha Release and tag it also as a research issue. If this is the issue that is required collaboration with Logan and so its semi-blocked then make a note of that and we may decided to let float to the beta release since it may require cooperation with the CitySDK folks and in the meantime we can develop a way to guard against the bad data pulls by notify the user of the problem. This does not need to hold up this PR.

**Review by ravenusmc — APPROVED** [review]

**Comment by hardnett** [comment]
Hi @mezerotm. Before I make this PR merge, I want to make sure that my assertion is correct that this PR can be merged and that bad data issues can be resolved via an additional issue. Thanks, and so if you are okay, just approve.

**Review by mezerotm — APPROVED** [review]

**Pull request merged**
